# Generated by Django 5.2.4 on 2025-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_watchedhistory_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
